//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketUygulamaSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket
    {
        public int anketId { get; set; }
        public string anketAdi { get; set; }
        public string anketTur { get; set; }
        public int anketSoruSayisi { get; set; }
        public int anketKullaniciId { get; set; }
        public Nullable<System.DateTime> gTarih { get; set; }
        public Nullable<int> sinir { get; set; }
        public Nullable<System.DateTime> oTarih { get; set; }
        public Nullable<int> gorunurluk { get; set; }
    }
}
