//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketUygulamaSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnketEntities : DbContext
    {
        public AnketEntities()
            : base("name=AnketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anket> Anket { get; set; }
        public virtual DbSet<AnketTipleri> AnketTipleri { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Secenekler> Secenekler { get; set; }
        public virtual DbSet<Sorular> Sorular { get; set; }
        public virtual DbSet<SoruTipleri> SoruTipleri { get; set; }
    }
}
