//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketUygulamaSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secenekler
    {
        public int secenekId { get; set; }
        public string secenekMetni { get; set; }
        public int soruId { get; set; }
    }
}
